import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const read = (path) => readFileSync(new URL('../' + path, import.meta.url), 'utf8')

test('route arche conservée séparément du réseau pro et des rendez-vous', () => {
  const app=read('src/App.jsx')
  assert.match(app, /import ArchePage from '\.\/components\/ArchePage'/)
  assert.match(app, /p === '\/arche' \? 'arche'/)
  assert.match(app, /view === 'arche'[\s\S]*<ArchePage onBack=\{backHome\} onNavigate=\{legalNav\}/)
  assert.match(read('scripts/apply-lumia-assistant-console.mjs'), /view !== 'arche'/)
})

test('la découverte renvoie vers une page de connexion simulée puis une application', () => {
  const page=read('src/components/ArchePage.jsx')
  const experience=read('src/components/ArcheSocialPrototype.jsx')
  assert.match(page, /data-arche-prototype="v2"/)
  assert.match(page, /setScreen\('login'\)/)
  assert.match(page, /screen === 'login'/)
  assert.match(page, /ArcheLoginPreview onBack=/)
  assert.match(page, /screen === 'app'/)
  assert.match(page, /ArcheAppPreview nickname=\{appNickname\} onExit=/)
  assert.match(experience, /id="connexion"/)
  assert.match(experience, /J’ai un compte/)
  assert.match(experience, /Créer un compte/)
  assert.match(experience, /Ne saisissez aucun vrai mot de passe ici/)
  assert.match(experience, /aucun compte n’est créé, aucun message n’est envoyé/)
  assert.match(experience, /onEnter\(pseudo\.trim\(\)\)/)
})

test('application sociale locale : fil, cercles, salon, messages, statut et interactions', () => {
  const page=read('src/components/ArcheSocialPrototype.jsx')
  for(const section of ['Le Fil','Grand Salon','Les Cercles','Rencontres','Mon profil']) assert.ok(page.includes(section),section)
  assert.match(page,/EXAMPLE_POSTS/)
  assert.match(page,/EXAMPLE_CHAT/)
  assert.match(page,/const submitPost=/)
  assert.match(page,/const submitChat=/)
  assert.match(page,/const submitDm=/)
  assert.match(page,/const \[likes,setLikes\]/)
  assert.match(page,/const \[replies,setReplies\]/)
  assert.match(page,/const \[presence,setPresence\]/)
  assert.match(page,/value="invisible"/)
})

test('messages privés seulement après invitation acceptée et Toc toc contrôlé', () => {
  const page=read('src/components/ArcheSocialPrototype.jsx')
  assert.match(page,/const \[contact,setContact\]=useState\('request'\)/)
  assert.match(page,/setContact\('accepted'\)/)
  assert.match(page,/contact==='accepted'/)
  assert.match(page,/contact!=='accepted'/)
  assert.match(page,/contact==='blocked'/)
  assert.match(page,/const \[allowToc,setAllowToc\]/)
  assert.match(page,/!allowToc\|\|contact!=='accepted'\|\|Date\.now\(\)-lastToc<10000/)
  assert.match(page,/typeof navigator\.vibrate==='function'/)
  assert.match(page,/navigator\.vibrate\(\[90,45,90\]\)/)
  assert.match(page,/prefers-reduced-motion:reduce/)
  assert.match(page,/vibration non disponible sur ce navigateur/)
  assert.doesNotMatch(page,/new Notification\(|new Audio\(/)
})

test('maquette sans écriture Supabase, réseau ou création de compte réelle', () => {
  const page=read('src/components/ArcheSocialPrototype.jsx')
  assert.match(page,/data-arche-app-preview="local-only"/)
  assert.match(page,/aucune donnée enregistrée ou envoyée/)
  assert.doesNotMatch(page,/supabase|\.insert\(|\.upsert\(|\.from\(|\bfetch\s*\(|axios|signInWithPassword|signUp\(|localStorage|sessionStorage/)
})

test('protection de la vie privée et anti-démarchage affichés', () => {
  const page=read('src/components/ArchePage.jsx')
  const app=read('src/components/ArcheSocialPrototype.jsx')
  assert.match(page,/Ni plateforme de voyance/)
  assert.match(page,/Ni concours de spiritualité/)
  assert.match(page,/Aucun démarchage en privé/)
  assert.match(app,/Seuls les membres de L’Arche pourront consulter votre fiche/)
  assert.match(app,/fermés pendant le premier pilote/)
  assert.match(app,/pas de démarchage/i)
})

test('charte visuelle MediumIA et SEO noindex pendant la prévisualisation', () => {
  const page=read('src/components/ArchePage.jsx')
  const app=read('src/components/ArcheSocialPrototype.jsx')
  assert.match(page,/MEDIUMIA_symbol_header\.png/)
  assert.match(page,/Un seul compte MediumIA/)
  assert.match(page,/Aucun achat ni aucune formation/)
  assert.match(app,/#1A1535/)
  assert.match(app,/#C9A84C/)
  assert.match(app,/#FAFAF7/)
  const meta=read('scripts/apply-route-seo-cro.mjs')
  const prerender=read('scripts/prerender-route-meta.mjs')
  assert.match(meta,/arche: \{\n    title: 'L’Arche — Communauté spirituelle gratuite/)
  assert.match(meta,/robots: 'noindex,nofollow'/)
  assert.match(prerender,/arche: '\/arche'/)
})
