export const SOLAR_TEMPERAMENTS = {
  Bélier: {
    symbol: '♈',
    element: 'Feu',
    modality: 'Cardinal',
    keywords: ['franc', 'impulsif', 'conquérant'],
    naturalForce: 'Élan, courage, capacité à ouvrir une voie et à agir sans attendre que tout soit parfait.',
    tensionReflex: 'Accélérer, trancher vite ou vouloir provoquer une réponse immédiate lorsque l’attente devient inconfortable.',
    movement: 'Avancer par décision, défi et mise en mouvement concrète.',
    vigilance: 'Ne pas confondre vitesse et clarté, surtout quand une situation demande de laisser le réel répondre.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament peut pousser à vouloir créer soi-même le prochain mouvement. MAX aide alors à distinguer l’action utile de l’action qui force une ouverture.',
  },
  Taureau: {
    symbol: '♉',
    element: 'Terre',
    modality: 'Fixe',
    keywords: ['stable', 'sensoriel', 'tenace'],
    naturalForce: 'Endurance, loyauté, sens du concret et capacité à construire dans la durée.',
    tensionReflex: 'S’accrocher à ce qui rassure ou retarder une rupture de rythme même quand le contexte a déjà changé.',
    movement: 'Avancer lentement mais solidement, en privilégiant ce qui peut durer.',
    vigilance: 'Ne pas transformer la stabilité en immobilité lorsque la trajectoire demande une adaptation.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament peut maintenir longtemps une position cohérente. MAX devient utile pour voir si cette constance nourrit encore la trajectoire ou si elle la fige.',
  },
  Gémeaux: {
    symbol: '♊',
    element: 'Air',
    modality: 'Mutable',
    keywords: ['curieux', 'mobile', 'communicant'],
    naturalForce: 'Souplesse mentale, curiosité, talent pour relier les idées et reformuler une situation.',
    tensionReflex: 'Multiplier les hypothèses, les messages ou les scénarios quand une réponse manque.',
    movement: 'Avancer par échange, compréhension et changement de point de vue.',
    vigilance: 'Ne pas remplacer une décision par une accumulation d’interprétations.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament remarque très vite les nouveaux signaux. MAX aide à distinguer une évolution réelle d’un simple changement de lecture.',
  },
  Cancer: {
    symbol: '♋',
    element: 'Eau',
    modality: 'Cardinal',
    keywords: ['protecteur', 'réceptif', 'mémoire'],
    naturalForce: 'Sensibilité, intuition relationnelle, mémoire fine des liens et instinct de protection.',
    tensionReflex: 'Se replier, protéger l’ancien ou lire le présent à travers une blessure passée.',
    movement: 'Avancer lorsqu’un sentiment de sécurité intérieure permet de quitter la défensive.',
    vigilance: 'Ne pas confondre fidélité émotionnelle et obligation de maintenir un cycle ouvert.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament garde la trace de ce qui a compté. MAX peut montrer ce qui appartient encore au présent et ce qui appartient surtout à la mémoire du lien.',
  },
  Lion: {
    symbol: '♌',
    element: 'Feu',
    modality: 'Fixe',
    keywords: ['rayonnant', 'loyal', 'créatif'],
    naturalForce: 'Présence, générosité, créativité et capacité à défendre ce qui a du sens avec cœur.',
    tensionReflex: 'Vivre une absence de reconnaissance comme une remise en cause personnelle ou vouloir garder une position digne coûte que coûte.',
    movement: 'Avancer lorsqu’il peut agir avec fierté, cohérence et expression personnelle.',
    vigilance: 'Ne pas laisser l’orgueil empêcher une réévaluation sincère de la trajectoire.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament cherche une trajectoire qui ait du sens et de la noblesse. MAX aide à voir si la fidélité à une histoire reste vivante ou devient surtout une question d’identité.',
  },
  Vierge: {
    symbol: '♍',
    element: 'Terre',
    modality: 'Mutable',
    keywords: ['précis', 'utile', 'analytique'],
    naturalForce: 'Discernement, sens du détail, capacité à corriger ce qui peut réellement être amélioré.',
    tensionReflex: 'Sur-analyser, chercher l’erreur cachée ou vouloir résoudre une situation avant qu’elle soit mûre.',
    movement: 'Avancer par ajustements concrets, méthode et clarification progressive.',
    vigilance: 'Ne pas attendre une cohérence parfaite avant de reconnaître ce que le réel montre déjà.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament repère les micro-changements. MAX aide à hiérarchiser ceux qui modifient vraiment la trajectoire.',
  },
  Balance: {
    symbol: '♎',
    element: 'Air',
    modality: 'Cardinal',
    keywords: ['relationnel', 'nuancé', 'harmonisant'],
    naturalForce: 'Sens de l’équilibre, capacité à voir plusieurs points de vue et à chercher une forme juste de relation.',
    tensionReflex: 'Retarder un choix, lisser un conflit ou rester trop longtemps entre deux options pour préserver l’harmonie.',
    movement: 'Avancer par dialogue, mise en balance et décision relationnelle claire.',
    vigilance: 'Ne pas sacrifier sa propre position pour éviter temporairement une tension.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament observe beaucoup la qualité du lien. MAX aide à voir si l’équilibre évolue réellement ou si seule la forme du dialogue change.',
  },
  Scorpion: {
    symbol: '♏',
    element: 'Eau',
    modality: 'Fixe',
    keywords: ['profond', 'stratégique', 'transformateur'],
    naturalForce: 'Intensité, persévérance, lucidité sur les zones cachées et capacité à traverser des transformations profondes.',
    tensionReflex: 'Chercher à contrôler ce qui échappe, se méfier des réponses incomplètes ou rester relié à une situation tant qu’elle ne semble pas totalement résolue.',
    movement: 'Avancer par vérité, dépouillement et transformation plutôt que par compromis superficiel.',
    vigilance: 'Ne pas attendre une clôture parfaite pour autoriser une nouvelle étape à commencer.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament peut garder longtemps actif ce qui reste émotionnellement inachevé. MAX aide à voir si le cycle travaille encore réellement ou si l’intensité intérieure prolonge seule son importance.',
  },
  Sagittaire: {
    symbol: '♐',
    element: 'Feu',
    modality: 'Mutable',
    keywords: ['expansif', 'franc', 'explorateur'],
    naturalForce: 'Élan vers le sens, optimisme, besoin d’élargir l’horizon et capacité à rebondir.',
    tensionReflex: 'Se projeter vite vers la suite ou donner un sens global à une situation avant d’avoir vérifié les faits.',
    movement: 'Avancer par exploration, vision et ouverture de nouvelles possibilités.',
    vigilance: 'Ne pas confondre une possibilité enthousiasmante avec une direction déjà confirmée.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament repère vite les portes de sortie et les nouveaux horizons. MAX aide à voir lesquelles deviennent réellement consistantes.',
  },
  Capricorne: {
    symbol: '♑',
    element: 'Terre',
    modality: 'Cardinal',
    keywords: ['structuré', 'endurant', 'responsable'],
    naturalForce: 'Patience, sens de la stratégie, capacité à construire malgré les délais et à tenir une direction.',
    tensionReflex: 'Porter trop longtemps une situation par devoir, contrôle ou peur de perdre l’investissement déjà consenti.',
    movement: 'Avancer par étapes, décisions responsables et consolidation progressive.',
    vigilance: 'Ne pas confondre persévérance et maintien automatique d’une structure devenue vide.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament supporte bien la durée. MAX devient précieux pour distinguer une maturation lente d’un cycle qui ne progresse plus.',
  },
  Verseau: {
    symbol: '♒',
    element: 'Air',
    modality: 'Fixe',
    keywords: ['indépendant', 'visionnaire', 'atypique'],
    naturalForce: 'Originalité, autonomie mentale, capacité à sortir d’un cadre et à penser autrement.',
    tensionReflex: 'Prendre de la distance trop vite, intellectualiser ou défendre une vision par principe.',
    movement: 'Avancer lorsqu’une nouvelle logique devient plus cohérente que l’ancien cadre.',
    vigilance: 'Ne pas utiliser le détachement pour éviter ce qui demande encore une implication émotionnelle claire.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament détecte les ruptures de modèle. MAX aide à voir si le changement vient vraiment du réel ou surtout d’un besoin de respirer hors de l’ancien cadre.',
  },
  Poissons: {
    symbol: '♓',
    element: 'Eau',
    modality: 'Mutable',
    keywords: ['réceptif', 'imaginatif', 'intuitif'],
    naturalForce: 'Grande réceptivité, imagination, empathie et capacité à sentir les nuances d’une situation.',
    tensionReflex: 'Fusionner avec une possibilité, idéaliser un lien ou laisser plusieurs scénarios rester ouverts trop longtemps.',
    movement: 'Avancer par intuition, inspiration et acceptation progressive de ce qui se révèle.',
    vigilance: 'Ne pas confondre ressenti profond, espoir et information réellement confirmée.',
    lineTimeLens: 'Dans une Ligne de Temps, ce tempérament ressent très fort les possibles. MAX aide à séparer ce qui est symboliquement vivant de ce qui est concrètement en train d’évoluer.',
  },
}

function normalizeSignName(value) {
  const raw = String(value || '').trim()
  if (!raw) return ''
  const match = Object.keys(SOLAR_TEMPERAMENTS).find((sign) => sign.localeCompare(raw, 'fr', { sensitivity: 'base' }) === 0)
  return match || ''
}

export function getSolarTemperament(sign) {
  const normalized = normalizeSignName(sign)
  if (!normalized) return null
  return {
    sign: normalized,
    ...SOLAR_TEMPERAMENTS[normalized],
  }
}
