import { useState } from 'react'
import LegalFooter from './LegalFooter'
import { ArcheAppPreview } from './ArcheSocialPrototype'

function LoginScreen({ onBack, onEnter }) {
  const [pseudo, setPseudo] = useState('Étoile du Nord')
  const [ack, setAck] = useState(false)
  return <div className="min-h-screen bg-white text-[#1A1535]">
    <header className="border-b border-[#ECEAF2] bg-white px-5 py-4 md:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><p className="font-georgia text-xl tracking-[.05em]">L’ARCHE</p><button type="button" onClick={onBack} className="min-h-11 rounded-full border border-[#ECEAF2] bg-white px-4 py-2 text-sm font-semibold text-[#1A1535] hover:bg-[#FAFAF7]">← Découverte</button></div></header>
    <main className="px-5 py-20 md:px-8"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1fr_420px]">
      <div><p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#4A3F6B]">Accès membres · démonstration</p><h1 className="max-w-xl font-georgia text-4xl leading-tight md:text-5xl">Entrez dans L’Arche.</h1><p className="mt-6 max-w-xl text-base leading-8 text-[#4A3F6B]">Un espace blanc, clair et social : Fil vivant, ambiances de publications, Cercles, proches, présence et Lueur. Aucune donnée réelle n’est envoyée.</p></div>
      <form onSubmit={(event) => { event.preventDefault(); if (ack && pseudo.trim()) onEnter(pseudo.trim()) }} className="rounded-3xl border border-[#ECEAF2] bg-white p-6 shadow-[0_22px_70px_rgba(26,21,53,.08)]">
        <label className="block text-sm font-semibold">Pseudonyme fictif<input required maxLength={32} autoComplete="off" value={pseudo} onChange={(event) => setPseudo(event.target.value)} className="mt-2 min-h-11 w-full rounded-2xl border border-[#ECEAF2] bg-white px-4 py-3 text-sm text-[#1A1535] outline-none focus:border-[#4A3F6B]"/></label>
        <label className="mt-5 flex items-start gap-3 text-xs leading-5 text-[#4A3F6B]"><input required checked={ack} onChange={(event) => setAck(event.target.checked)} type="checkbox" className="mt-1 h-4 w-4 accent-[#1A1535]"/><span>Je comprends qu’il s’agit d’une simulation locale : aucun compte, message ou profil réel n’est créé.</span></label>
        <button disabled={!ack || !pseudo.trim()} className="mt-6 min-h-11 w-full rounded-full bg-[#1A1535] px-5 py-3 text-sm font-semibold text-white hover:bg-[#2B254D] disabled:cursor-not-allowed disabled:opacity-40">Entrer dans l’application →</button>
      </form>
    </div></main>
  </div>
}

export default function ArchePage({ onBack, onNavigate }) {
  const [screen, setScreen] = useState('landing')
  const [nickname, setNickname] = useState(null)
  if (screen === 'login') return <LoginScreen onBack={() => setScreen('landing')} onEnter={(nextNickname) => { setNickname(nextNickname); setScreen('app') }} />
  if (screen === 'app') return <ArcheAppPreview nickname={nickname || 'Étoile du Nord'} onExit={() => setScreen('landing')} />
  return <div data-arche-prototype="v2" className="min-h-screen bg-white text-[#1A1535]">
    <header className="border-b border-[#ECEAF2] bg-white"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-5 md:px-8"><a href="/arche" className="flex items-center gap-3"><img src="/images/brand/MEDIUMIA_symbol_header.png" alt="" className="h-10 w-10 object-contain"/><span className="font-georgia text-xl font-semibold tracking-[0.075em]">L’ARCHE</span></a><nav className="flex flex-wrap items-center gap-x-5 gap-y-3 text-xs font-semibold md:text-sm"><a href="#vision" className="hover:underline">La vision</a><a href="#compte" className="hover:underline">Le compte</a><button type="button" onClick={() => setScreen('login')} className="hover:underline">Se connecter</button><a href="/" onClick={(event) => { if (!event.metaKey && !event.ctrlKey && onBack) { event.preventDefault(); onBack() } }} className="border border-[#ECEAF2] bg-white px-4 py-3 hover:bg-[#FAFAF7]">MediumIA ↗</a></nav></div></header>
    <main>
      <section id="vision" className="mx-auto grid max-w-6xl items-center gap-10 px-5 pb-20 pt-14 md:grid-cols-[1.06fr_.94fr] md:px-8 md:pb-24 md:pt-24"><div><p className="mb-6 text-xs font-bold uppercase tracking-[0.22em] text-[#4A3F6B]">Le réseau social spirituel · gratuit · en création</p><h1 className="max-w-[690px] font-georgia text-[clamp(2.7rem,5.5vw,5.6rem)] font-normal leading-[1.08] tracking-[-0.035em] text-[#1A1535]">Différents dans nos chemins.<br/><span className="italic">Reliés dans nos vies.</span></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-[#4A3F6B] md:text-xl">Un lieu pour celles et ceux qui veulent parler spiritualité, intuition, rêves ou questionnements intérieurs sans se sentir jugés.</p><div className="mt-8 flex flex-wrap items-center gap-3"><button type="button" onClick={() => setScreen('login')} className="inline-flex min-h-12 items-center justify-center bg-[#1A1535] px-6 py-3 font-semibold text-white hover:bg-[#2B254D]">Se connecter à L’Arche →</button><a href="#charte" className="inline-flex min-h-12 items-center justify-center border border-[#ECEAF2] px-6 py-3 font-semibold text-[#1A1535] hover:bg-[#FAFAF7]">Notre engagement</a></div><p className="mt-6 text-xs leading-relaxed text-[#4A3F6B]">Maquette privée. Aucune inscription réelle n’est ouverte.</p></div><div className="rounded-3xl border border-[#ECEAF2] bg-[#FAFAF7] p-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#4A3F6B]">Après connexion</p><div className="mt-5 grid gap-3"><div className="rounded-2xl bg-white p-5 shadow-sm"><strong>Le Fil</strong><p className="mt-1 text-sm text-[#4A3F6B]">Publications, ambiances, questions et réponses sobres.</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><strong>Le Grand Salon</strong><p className="mt-1 text-sm text-[#4A3F6B]">Un espace direct pour se retrouver.</p></div><div className="rounded-2xl bg-white p-5 shadow-sm"><strong>Les Cercles</strong><p className="mt-1 text-sm text-[#4A3F6B]">Explorer par thèmes, sans hiérarchie.</p></div></div></div></section>
      <section id="compte" className="border-y border-[#ECEAF2] bg-[#FAFAF7] px-5 py-16 md:px-8"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#4A3F6B]">L’accès à la communauté</p><h2 className="mt-3 font-georgia text-3xl leading-tight text-[#1A1535] md:text-5xl">Un seul compte MediumIA.<br/>Une place à vous.</h2><p className="mt-5 text-sm leading-[1.85] text-[#4A3F6B]">Vous utiliserez votre compte MediumIA habituel ou en créerez un gratuitement. Aucun achat ni aucune formation ne sera nécessaire pour participer à L’Arche.</p></div><div className="rounded-3xl border border-[#ECEAF2] bg-white p-6"><p className="text-sm leading-7 text-[#4A3F6B]">Le profil L’Arche restera distinct des données privées du compte MediumIA. Les fiches de membres seront visibles uniquement par les membres de L’Arche, jamais par les visiteurs publics.</p><button type="button" onClick={() => setScreen('login')} className="mt-5 min-h-11 rounded-full bg-[#1A1535] px-5 py-3 text-sm font-semibold text-white">Essayer l’application →</button></div></div></section>
      <section id="charte" className="px-5 py-20 md:px-8"><div className="mx-auto max-w-6xl"><p className="mb-3 text-xs font-bold uppercase tracking-[0.23em] text-[#4A3F6B]">Notre charte fondatrice</p><h2 className="max-w-3xl font-georgia text-3xl leading-tight text-[#1A1535] md:text-5xl">On n’a rien à prouver pour mériter d’être écouté.</h2><div className="mt-10 grid gap-4 md:grid-cols-3"><article><h3 className="font-georgia text-xl">Accueillir sans hiérarchie</h3><p className="mt-3 text-sm leading-7 text-[#4A3F6B]">Croire, ne pas croire, chercher ou douter : chacun a sa place.</p></article><article><h3 className="font-georgia text-xl">Protéger la liberté</h3><p className="mt-3 text-sm leading-7 text-[#4A3F6B]">Aucun démarchage en privé, aucune pression pour consulter.</p></article><article><h3 className="font-georgia text-xl">Prendre soin des échanges</h3><p className="mt-3 text-sm leading-7 text-[#4A3F6B]">Signalement, blocage et modération humaine avant l’ouverture.</p></article></div></div></section>
    </main>
    <LegalFooter onNavigate={onNavigate}/>
  </div>
}
