-- Historical migration recovered from the deployed Supabase schema.

alter table public.agent_messages
  add column if not exists provider text,
  add column if not exists model text,
  add column if not exists sources jsonb not null default '[]'::jsonb;

create table if not exists public.agent_documents (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 240),
  source_type text not null default 'upload'
    check (source_type in ('upload', 'paste', 'url')),
  storage_bucket text,
  storage_path text,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes between 0 and 26214400),
  status text not null default 'uploaded'
    check (status in ('uploaded', 'processing', 'ready', 'error', 'archived')),
  approved_for_ai boolean not null default false,
  approved_at timestamptz,
  sensitivity text not null default 'confidential'
    check (sensitivity in ('normal', 'confidential', 'restricted')),
  version integer not null default 1 check (version > 0),
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_documents_storage_path_unique unique (storage_path),
  constraint uploaded_document_has_storage check (
    source_type <> 'upload' or (storage_bucket is not null and storage_path is not null)
  )
);

create index if not exists agent_documents_owner_agent_idx
  on public.agent_documents(owner_id, agent_id);
create index if not exists agent_documents_ready_idx
  on public.agent_documents(agent_id, approved_for_ai, status);
alter table public.agent_documents enable row level security;

create trigger agent_documents_set_updated_at
before update on public.agent_documents
for each row execute function public.set_updated_at();

create policy "Users can read own agent documents" on public.agent_documents
  for select to authenticated
  using (
    (select auth.uid()) = owner_id
    and exists (
      select 1 from public.agents a
      where a.id = agent_id and a.owner_id = (select auth.uid())
    )
  );
create policy "Users can create own agent documents" on public.agent_documents
  for insert to authenticated
  with check (
    (select auth.uid()) = owner_id
    and exists (
      select 1 from public.agents a
      where a.id = agent_id and a.owner_id = (select auth.uid())
    )
  );
create policy "Users can update own agent documents" on public.agent_documents
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check (
    (select auth.uid()) = owner_id
    and exists (
      select 1 from public.agents a
      where a.id = agent_id and a.owner_id = (select auth.uid())
    )
  );
create policy "Users can delete own agent documents" on public.agent_documents
  for delete to authenticated using ((select auth.uid()) = owner_id);

grant select, insert, update, delete on public.agent_documents to authenticated;

create table if not exists public.agent_document_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.agent_documents(id) on delete cascade,
  agent_id uuid not null references public.agents(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null check (char_length(content) between 1 and 12000),
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index)
);

create index if not exists agent_document_chunks_owner_agent_idx
  on public.agent_document_chunks(owner_id, agent_id);
create index if not exists agent_document_chunks_search_idx
  on public.agent_document_chunks using gin (to_tsvector('french', content));
alter table public.agent_document_chunks enable row level security;

create policy "Users can read own document chunks" on public.agent_document_chunks
  for select to authenticated
  using (
    (select auth.uid()) = owner_id
    and exists (
      select 1 from public.agent_documents d
      where d.id = document_id
        and d.owner_id = (select auth.uid())
        and d.agent_id = d.agent_id
    )
  );
create policy "Users can create own document chunks" on public.agent_document_chunks
  for insert to authenticated
  with check (
    (select auth.uid()) = owner_id
    and exists (
      select 1 from public.agent_documents d
      where d.id = document_id
        and d.owner_id = (select auth.uid())
        and d.agent_id = d.agent_id
    )
  );
create policy "Users can delete own document chunks" on public.agent_document_chunks
  for delete to authenticated using ((select auth.uid()) = owner_id);

grant select, insert, delete on public.agent_document_chunks to authenticated;

create table if not exists public.agent_audit_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  agent_id uuid references public.agents(id) on delete cascade,
  event_type text not null,
  resource_type text not null,
  resource_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_audit_events_agent_created_idx
  on public.agent_audit_events(agent_id, created_at desc);
create index if not exists agent_audit_events_owner_created_idx
  on public.agent_audit_events(owner_id, created_at desc);
alter table public.agent_audit_events enable row level security;

create policy "Users can read own audit events" on public.agent_audit_events
  for select to authenticated using ((select auth.uid()) = owner_id);
create policy "Users can create own audit events" on public.agent_audit_events
  for insert to authenticated
  with check (
    (select auth.uid()) = owner_id
    and (
      agent_id is null
      or exists (
        select 1 from public.agents a
        where a.id = agent_id and a.owner_id = (select auth.uid())
      )
    )
  );

grant select, insert on public.agent_audit_events to authenticated;

create policy "Users can upload own agent documents" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'agent-documents'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and exists (
      select 1 from public.agents a
      where a.owner_id = (select auth.uid())
        and a.id::text = (storage.foldername(a.name))[2]
    )
  );
create policy "Users can read own stored agent documents" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'agent-documents'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and owner_id = (select auth.uid())::text
  );
create policy "Users can delete own stored agent documents" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'agent-documents'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and owner_id = (select auth.uid())::text
  );

create or replace function public.search_agent_document_chunks(
  p_agent_id uuid,
  p_query text,
  p_limit integer default 6
)
returns table (
  chunk_id bigint,
  document_id uuid,
  document_name text,
  chunk_index integer,
  content text,
  rank real
)
language sql
stable
set search_path = public, pg_temp
as $$
  select
    c.id,
    c.document_id,
    d.name,
    c.chunk_index,
    c.content,
    ts_rank_cd(
      to_tsvector('french', c.content),
      plainto_tsquery('french', coalesce(p_query, ''))
    )::real as rank
  from public.agent_document_chunks c
  join public.agent_documents d on d.id = c.document_id
  where c.agent_id = p_agent_id
    and c.owner_id = (select auth.uid())
    and d.owner_id = (select auth.uid())
    and d.agent_id = p_agent_id
    and d.status = 'ready'
    and d.approved_for_ai = true
    and d.sensitivity <> 'restricted'
    and to_tsvector('french', c.content) @@ plainto_tsquery('french', coalesce(p_query, ''))
  order by rank desc, c.chunk_index asc
  limit greatest(1, least(coalesce(p_limit, 6), 12));
$$;

grant execute on function public.search_agent_document_chunks(uuid, text, integer)
  to authenticated;
